version: '2'

networks:
  local:
    driver: 'bridge'

services:
  elasticmq:
    build: .
    ports:
      - "9324:9324"
    environment: {}
    networks:
      local:
        aliases:
          - sqs.local
    restart: 'on-failure:30'
